using System;
using Core.Services;
using Domain.Board;
using PrimeTween;
using UnityEngine;
using UnityEngine.EventSystems;

namespace Presentation
{
    /// <summary>
    /// World-space sprite tile. Two <see cref="SpriteRenderer"/> children (base +
    /// fruit) + <see cref="BoxCollider2D"/> for taps via <see cref="IPointerClickHandler"/>
    /// through the existing EventSystem. Clicks work through the SAME uGUI event
    /// pipeline the HUD already uses — the gameplay Camera just needs a
    /// <c>Physics2DRaycaster</c> so 2D colliders participate; GameFlowController
    /// wires that up on Awake. No separate Input.GetMouseButtonDown polling.
    ///
    /// Draw order is driven by explicit <see cref="SpriteRenderer.sortingOrder"/>
    /// per layer (band = layer × 10), never by sibling index or transform.z — that
    /// is what fixes the pyramid sorting issues from the old uGUI implementation.
    /// The prefab lives at <c>Resources/Prefabs/TileView.prefab</c>, generated by
    /// <c>Tools ▸ Rebuild Tile Prefab</c>.
    /// </summary>
    [RequireComponent(typeof(BoxCollider2D))]
    public sealed class TileView : MonoBehaviour, IPointerClickHandler
    {
        [SerializeField] private SpriteRenderer _baseRenderer;
        [SerializeField] private SpriteRenderer _fruitRenderer;
        [SerializeField] private BoxCollider2D _collider;

        /// <summary>Every board layer bumps sortingOrder by this amount so a layer's
        /// intra-grid sub-order (see <see cref="ApplySortingOrder"/>) can never spill
        /// into the next layer's band. 100 gives room for a 10×10 grid per layer.</summary>
        private const int SortingOrderPerLayer = 100;

        private TileModel _tile;
        private Action<TileId> _onClicked;
        private Sequence _flySequence;
        private Tween _hintTween;
        private Vector3 _restScale;
        private bool _flying;

        public TileModel Model => _tile;

        private void Reset()
        {
            _baseRenderer = transform.Find("Base")?.GetComponent<SpriteRenderer>();
            _fruitRenderer = transform.Find("Fruit")?.GetComponent<SpriteRenderer>();
            _collider = GetComponent<BoxCollider2D>();
        }

        private void Awake()
        {
            if (_collider == null) _collider = GetComponent<BoxCollider2D>();
            _restScale = transform.localScale == Vector3.zero ? Vector3.one : transform.localScale;
        }

        public void Initialize(TileModel tile, Sprite baseSprite, Sprite fruitSprite, Action<TileId> onClicked)
        {
            _tile = tile;
            _onClicked = onClicked;
            if (baseSprite != null && _baseRenderer != null) _baseRenderer.sprite = baseSprite;
            if (_fruitRenderer != null) _fruitRenderer.sprite = fruitSprite;

            _restScale = transform.localScale;
            _flying = false;
            if (_baseRenderer != null) _baseRenderer.color = Color.white;
            if (_fruitRenderer != null) _fruitRenderer.color = Color.white;

            ApplySortingOrder(tile.Coordinate.Layer, tile.Coordinate.X, tile.Coordinate.Y);
            UpdateVisuals();
        }

        /// <summary>
        /// Draw-order rule:
        ///   sortingOrder = layer × 100 + Y × 10 + X + subOrder
        /// - Layer band (×100) guarantees an upper-layer tile always draws in
        ///   front of any lower-layer tile.
        /// - Within a layer, higher Y (visually further down on screen) draws in
        ///   front of lower Y, and higher X (further right in a row) draws in
        ///   front of lower X — matches the user's "tile at (1,1) sits on top
        ///   of tile at (0,1)" rule.
        /// - +0/+1 subOrder pins the fruit above the base within one tile.
        /// </summary>
        public void ApplySortingOrder(int layer, int x, int y)
        {
            var band = layer * SortingOrderPerLayer + y * 10 + x;
            if (_baseRenderer != null) _baseRenderer.sortingOrder = band;
            if (_fruitRenderer != null) _fruitRenderer.sortingOrder = band + 1;
        }

        public void OverrideSortingOrder(int baseOrder)
        {
            if (_baseRenderer != null) _baseRenderer.sortingOrder = baseOrder;
            if (_fruitRenderer != null) _fruitRenderer.sortingOrder = baseOrder + 1;
        }

        public void UpdateVisuals()
        {
            if (_tile == null) return;
            var covered = _tile.State == TileState.Covered;

            if (_fruitRenderer != null) _fruitRenderer.enabled = !covered;
            if (_baseRenderer != null) _baseRenderer.color = covered ? new Color(0.35f, 0.32f, 0.3f) : Color.white;

            _collider.enabled = _tile.IsSelectable && !_flying;
        }

        public void OnPointerClick(PointerEventData eventData)
        {
            if (_tile == null || !_tile.IsSelectable || _flying) return;
            _onClicked?.Invoke(_tile.Id);
            PlayClickAnimation();
            WorldParticleBurst.BurstSparkle(transform.position, count: 5, duration: 0.3f, distance: 0.4f);
            if (GameServices.IsRegistered)
            {
                GameServices.Haptics.Play(HapticStrength.Light);
                GameServices.Audio.PlaySfx("TileSelectSound");
            }
        }

        public void PlayClickAnimation()
        {
            Tween.PunchScale(transform, new Vector3(0.22f, -0.18f, 0f), 0.25f, frequency: 10);
        }

        /// <summary>
        /// Fly this tile from wherever it is now to the exact tray slot world
        /// position at the exact slot icon world scale, then invoke
        /// <paramref name="onLanded"/>. Reparents to <paramref name="flyLayer"/>
        /// with an elevated <paramref name="flyingSortingOrder"/> so nothing on the
        /// board or the tray can occlude it during flight. Landing is a snap — the
        /// tile does NOT fade; GameFlowController is responsible for enabling the
        /// slot's icon on the same frame this callback fires and destroying this
        /// GameObject, so the transition reads as the tile becoming the slot.
        /// </summary>
        public void FlyToSlot(
            Vector3 targetWorldPos,
            Vector3 targetWorldScale,
            Transform flyLayer,
            int flyingSortingOrder,
            Action onLanded)
        {
            _flying = true;
            _collider.enabled = false;

            transform.SetParent(flyLayer, worldPositionStays: true);
            OverrideSortingOrder(flyingSortingOrder);

            var startPos = transform.position;
            var arcPeak = Vector3.Lerp(startPos, targetWorldPos, 0.5f) + Vector3.up * 1.6f;
            var spin = UnityEngine.Random.value > 0.5f ? 1f : -1f;

            var rise = Tween.Position(transform, arcPeak, 0.18f, Ease.OutSine);
            _flySequence = Sequence.Create(rise)
                .Chain(Tween.Position(transform, targetWorldPos, 0.22f, Ease.InSine));

            Tween.Scale(transform, targetWorldScale, 0.4f, Ease.OutQuad);
            Tween.EulerAngles(transform, Vector3.zero, new Vector3(0f, 0f, 22f * spin), 0.4f, Ease.OutQuad)
                .OnComplete(() => onLanded?.Invoke());
        }

        public void PlayWinAnimation()
        {
            Tween.Scale(transform, _restScale * 1.1f, 0.35f, Ease.OutBack, cycles: 6, cycleMode: CycleMode.Yoyo);
        }

        public void PlayLoseAnimation()
        {
            Tween.PunchScale(transform, new Vector3(0.08f, 0.08f, 0f), 0.4f);
        }

        public void PlayHintPulse()
        {
            if (_hintTween.isAlive) _hintTween.Stop();
            transform.localScale = _restScale;
            _hintTween = Tween.Scale(transform, _restScale * 1.15f, 0.25f, Ease.InOutSine, cycles: 4, cycleMode: CycleMode.Yoyo);
        }

        public void CancelAllAnimations()
        {
            if (_flySequence.isAlive) _flySequence.Stop();
            if (_hintTween.isAlive) _hintTween.Stop();
            Tween.StopAll(transform);
        }
    }
}
